name: thebarkingtrout
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4375
  lightness: 0.035281507996842265
  saturation: 0.13313491363078356
  rhythmicContrast: 0.39652994251810014
purpose: []
